---
abstract: 'Provides mro functions for XS modules'
author:
  - 'Goro Fuji(gfx) <gfuji(at)cpan.org>.'
build_requires:
  ExtUtils::Depends: 0
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.44
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-MRO
no_index:
  directory:
    - example
    - benchmark
    - inc
    - t
requires:
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
